### ISSUE TITLE
Design application deletion strategy

### ISSUE THREAD

**Issue by whitlockjc** [30x/shipyard#3]
Deleting Shipyard applications means deleting the Docker images associated with the application.  Where things need to get interesting is when you delete a running application.  If you delete the images of a running application, when Kubernetes moves the deployment pods the image will not be available and the new pods will be in an `Error` or `Pending` state forever.

So how do we want to handle deleting running applications?  My initial thoughts on this are that deleting a running application you should get an error.  But I also think it would be nice to have a flag that would allow you to indicate that you're aware the application is running and that you want to undeploy the application first and _then_ delete the application.

Thoughts?

**Comment by whitlockjc** [comment]
One thing to keep in mind here is that this will also mean that now `kiln` depends on `enrober`.  This is not currently the case.

**Comment by noahdietz** [comment]
Should we push the dependency back on the cli/eventual UI?

So instead of having `kiln` make a call to `enrober` to check for active deployments with the app in question, can we have `shipyardctl` (and whatever UI we have in the future) first do a check for active deployments _then_ determine if deleting is safe/force it?

**Comment by AdamMagaluk** [comment]
I don't think i'd agree in this case of having the cli/ui have that type of responsibility. I think it works ok with creating/updating a resource because the worst that can happen with the wrong api call is a error returned. On the other hand deleting a deployed image will mess up a deployed application.

**Comment by whitlockjc** [comment]
I agree with @AdamMagaluk. I don't want to make it where not using `shipyardctl` would allow you to wedge things.

**Comment by whitlockjc** [comment]
I'm not advocating for this completely but maybe it's time we collapse `kiln` and `enrober` into one deliverable?  We can still have separate packages for their code to allow multiple people to work on the different pieces at the same time.

I have not put a lot of thought into this yet but it's something we should discuss.

**Comment by whitlockjc** [comment]
After talking offline, here is the plan:

1. Break out the reusable code from `enrober` into a package that both `enrober` and `kiln` can share _(if there is any code to share)_
2. Put the Shipyard configuration into a `ConfigMap` so that all components can share the same configuration _(where necessary)_ without fear of mistyping things when configuring their component
3. `kiln` will now use this new shared code _(if there is any)_ and configuration to query Kubernetes directly to check and see if the application deleted is running or not _(instead of querying `enrober` directly)_
4. `kiln` will not support the `--force` flag for `shipyardctl delete application` and the _force_ support will be `shipyardctl` only _(for now)_

**Comment by noahdietz** [comment]
This was implemented and introduced in kiln [#84](https://github.com/30x/kiln/pull/84) & shipyardctl [#72](https://github.com/30x/shipyardctl/pull/72).

I believe we can close.
