### ISSUE TITLE
Allow specifying environment variables when generating a pod template spec

### ISSUE THREAD

**Issue by whitlockjc** [30x/shipyard#37]
Many applications use environment variables for runtime configuration and without the ability to specify environment variables when generating the PTS, generating a PTS is not very useful.

**Comment by noahdietz** [comment]
Environment variables will be specified by client at image build time and baked into the Dockerfile, pre-build, thus they are built into the image pulled by the PTS. 

_For documentation:_ 
* these env variables **should not** contain sensitive information (i.e. secrets, tokens, etc) as they are insecure.
* PTS ("deployment-time") specified env variables will override duplicates specified in the Dockerfile ("build-time")

The other option was using the PTS URL as "storage" and encoding these env variables into the query string.
