### ISSUE TITLE
Filter namespaces based on auth

### ISSUE THREAD

**Issue by tnine** [30x/shipyard#39]
We should filter namespaces based on the JWT token on the GET of /namespaces.  If you're not allowed to view a namespace, it should not be returned.

**Comment by mpnally** [comment]
I agree that is probably the ideal, although it might not be too bad to show people the names of the ones that they can't access if the implementation of the ideal is hard.

**Comment by tnine** [comment]
This is done, just working on auth issues with spaces and '+' characters before pushing
