### ISSUE TITLE
Remove ability to delete/replace application revisions

### ISSUE THREAD

**Issue by whitlockjc** [30x/shipyard#4]
Per today's standup parking lot, for now we will remove the ability to delete any application revision and/or replace any application revision.

**Comment by whitlockjc** [comment]
It looks like https://github.com/30x/shipyardctl/issues/58 was intended to implement the replace functionality so feel free to close that as well.

**Comment by noahdietz** [comment]
Finished per kiln [#84](https://github.com/30x/kiln/pull/84) and shipyardctl [#72](https://github.com/30x/shipyardctl/pull/72)

We can close.
