### ISSUE TITLE
Investigate combining enrober and kiln

### ISSUE THREAD

**Issue by whitlockjc** [30x/shipyard#7]
The past few weeks we've implemented features in `enrober` and `kiln` that are making the two services somewhat tightly coupled.  Recent development has also brought to light that even without the two currently depending on each other, there is the possibility of a configuration mismatch where one could be configured in a way that it doesn't work properly with the other.

This being said, I would like to discuss whether it makes sense to combine `enrober` and `kiln` into a single service.  I'm not suggesting we do this, I'm suggesting we discuss the possibility of doing this.

Initial thoughts are that we cannot combine them as-is.  The main reason is due to `kiln`'s ECR secret management basically kills the whole pod whenever the ECR secrets change.  Killing the whole Shipyard API on a 6hr interview is not an option, although one could question if Shipyard were public now would this even be ideal for `kiln`?

Here are some possible ideas on how to handle this:

1. Figure out a better way to refresh the ECR secrets in `kiln` without killing the entire Pod
2. Investigate using a Docker registry that allows long-lived secrets
3. Not combine the two and just centralize the shared code so that the two services do not depend on each other.
4. Not combine the two and use convention, like labeling the latest images appropriately, so that the two services do not depend on each other.

I'm all ears and the list above is just off the top of my head.

**Comment by mpnally** [comment]
This seems counter to the spirit of micro-services and Kubernetes. I think
we should be looking for opportunities to break existing things into
smaller and smaller units, not combine them. Maybe you can explain more what the coupling is between the two?

**Comment by whitlockjc** [comment]
I understand but when you have circular dependencies that create brittle wiring, it needs to be looked it.  I'm only suggesting we look at the situation.

**Comment by mpnally** [comment]
Can you explain the circular dependencies?

**Comment by whitlockjc** [comment]
`enrober` queries `kiln` to get images details so that deploying without a revision deployed the latest image.  _(Not implemented yet but it came up)_ and `kiln` queries `enrober` when deleting applications to see if it's running before deleting.  They both share configuration that if configured differently, things won't work.

When these issues started coming up, or even the possibility, it just made sense to look at this again.  If `enrober` cannot work fully without `kiln` and vice versa, it just seemed like a good idea to look at the matter more.

**Comment by mpnally** [comment]
I would not expect `enrober` to depend on `kiln` to know what the latest revision is. Would you not want `enrober` to work with all images, not just ones built by `kiln`? I thought it was standard behavior of Docker registries to automatically associate the tag 'latest' with the latest image, so you should be able to get the latest revision that way. Perhaps the problem is that we have combined two things in `kiln` that should be separate — 1) a service that builds Docker images 2) a shared service interface for our Docker registry. If that is the case, then a better solution would be to split 2) into a new micro-service that is used by `enrober` and `kiln`, or just teach `enrober` and `kiln` to talk to the registry directly. Having `kiln` talk to `enrober` to find out whether an image is in use seems reasonable — `enrober` is our interface to the cluster.

**Comment by whitlockjc** [comment]
That's not automatic behavior but we've talked about doing it to solve this.  Remember, I'm only tell you the needs that have come up that lead to in investigating the situation, I'm not advocating for anything.

**Comment by whitlockjc** [comment]
I've updated the list ideas to reflect the convention-based solution you mentioned _(we forgot to add it)_.

**Comment by mpnally** [comment]
Understand you are gathering thoughts and opinions and clarifying the problems — just putting my 2 cents in

**Comment by whitlockjc** [comment]
The plan for now is to keep `enrober` and `kiln` separate.  We will break out the reusable code between the two and also centralize the shared configuration in a `ConfigMap`.  This should solve any immediate concerns around code duplication, configuration brittleness and will not change the current lack of direct dependency between the two.
